import Head from "next/head";

import { ConnectButton } from "@rainbow-me/rainbowkit";
import {
  RouterContractInfo,
  AddContributor,
  RemoveContributor,
  ChangeOwner,
  AccountList,
  SendLumpSum,
  AllowAccount,
} from "@/components/contract";

import { GetAccountInfo } from "@/components/superfluid";

export default function Home() {
  return (
    <div className={"bg-sky-50"}>
      <Head>
        <title>Create-Web3 App</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header style={{ padding: "1rem" }}>
        <ConnectButton />
      </header>

      <main className={`p-8`}>
        <GetAccountInfo />
        <RouterContractInfo />
        <AllowAccount />
        <AddContributor />
        <RemoveContributor />
        <ChangeOwner />
        <AccountList />
        <SendLumpSum />
      </main>
    </div>
  );
}
