import Head from "next/head";

import { WelcomeContainer } from "@/components/containers";
import { GridLayout, GridItemTwo, GridItemEight } from "@/components/layout";

// import { UserContext } from "@/components/layout";
// import { useContext } from "react";

import { CreateTrust, TrustFactoryInfo, AddBeliever } from "@/components/trust";

import { GetAccountInfo } from "@/components/superfluid";

export default function Home() {
  // const { authenticatedCeramicInst } = useContext(UserContext);
  // const ceramic = authenticatedCeramicInst;

  // console.log(ceramic);

  return (
    <div className={"bg-slate-100"}>
      <Head>
        <title>Trust Factory</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GridLayout>
        <GridItemTwo> </GridItemTwo>
        <GridItemEight>
          <WelcomeContainer />
        </GridItemEight>
        <GridItemTwo> </GridItemTwo>
      </GridLayout>
    </div>
  );
}
