import Head from "next/head";

import { ConnectButton } from "@rainbow-me/rainbowkit";
import {
  RouterContractInfo,
  AddContributor,
  RemoveContributor,
  ChangeOwner,
  AccountList,
  SendLumpSum,
  AllowAccount,
  CreateFlow,
  WithdrawFunds,
} from "@/components/contract";

import { UserContext } from "@/components/layout";
import { useContext } from "react";

import { CreateTrust, TrustFactoryInfo } from "@/components/trust";

import { GetAccountInfo } from "@/components/superfluid";

export default function Home() {
  const { authenticatedCeramicInst } = useContext(UserContext);
  const ceramic = authenticatedCeramicInst;

  console.log(ceramic);

  return (
    <div className={"bg-slate-100"}>
      <Head>
        <title></title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`p-8`}>
        {/* <GetAccountInfo />
        <RouterContractInfo />
        <AllowAccount />
        <AddContributor />
        <RemoveContributor />
        <ChangeOwner />
        <AccountList />
        <SendLumpSum />
        <CreateFlow />
        <WithdrawFunds /> */}
        <CreateTrust />
        <TrustFactoryInfo />
      </main>
    </div>
  );
}
