import Head from "next/head";

import {
  RouterContractInfo,
  AddContributor,
  RemoveContributor,
  ChangeOwner,
  AccountList,
  SendLumpSum,
  AllowAccount,
  CreateFlow,
  WithdrawFunds,
} from "@/components/contract";

import { GetAccountInfo } from "@/components/superfluid";

export default function Stream() {
  return (
    <div className={"bg-slate-100"}>
      <Head>
        <title>Trust Factory</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`p-8`}>
        <GetAccountInfo />
        <RouterContractInfo />
        <AllowAccount />
        <AddContributor />
        <RemoveContributor />
        <ChangeOwner />
        <AccountList />
        <SendLumpSum />
        <CreateFlow />
        <WithdrawFunds />
      </main>
    </div>
  );
}
